create table candidato (
DATA_GERACAO varchar(255),
HORA_GERACAO varchar(255),
ANO_ELEICAO int,
NUM_TURNO int,
DESCRICAO_ELEICAO varchar(255),
SIGLA_UF varchar(255),
SIGLA_UE varchar(255),
CODIGO_MUNICIPIO int,
NOME_MUNICIPIO varchar(255),
NUMERO_ZONA varchar(255),
CODIGO_CARGO int,
NUMERO_CAND int,
SQ_CANDIDATO int,
NOME_CANDIDATO varchar(255),
NOME_URNA_CANDIDATO varchar(255),
DESCRICAO_CARGO varchar(255),
COD_SIT_CAND_SUPERIOR varchar(255),
DESC_SIT_CAND_SUPERIOR varchar(255),
CODIGO_SIT_CANDIDATO varchar(255),
DESC_SIT_CANDIDATO varchar(255),
CODIGO_SIT_CAND_TOT varchar(255),
DESC_SIT_CAND_TOT varchar(255),
NUMERO_PARTIDO int,
SIGLA_PARTIDO varchar(255),
NOME_PARTIDO varchar(255),
SEQUENCIAL_LEGENDA varchar(255),
NOME_COLIGACAO varchar(255),
COMPOSICAO_LEGENDA varchar(255),
TOTAL_VOTOS int
);

create table detalhe_votacao (
DATA_GERACAO varchar(255),
HORA_GERACAO varchar(255),
ANO_ELEICAO varchar(255),
NUM_TURNO int,
DESCRICAO_ELEICAO varchar(255),
SIGLA_UF varchar(255),
SIGLA_UE varchar(255),
CODIGO_MUNICIPIO int,
NOME_MUNICIPIO varchar(255),
NUMERO_ZONA varchar(255),
CODIGO_CARGO varchar(255),
DESCRICAO_CARGO varchar(255),
QTD_APTOS int,
QTD_SECOES varchar(255),
QTD_SECOES_AGREGADAS varchar(255),
QTD_APTOS_TOT int,
QTD_SECOES_TOT varchar(255),
QTD_COMPARECIMENTO varchar(255),
QTD_ABSTENCOES varchar(255),
QTD_VOTOS_NOMINAIS varchar(255),
QTD_VOTOS_BRANCOS varchar(255),
QTD_VOTOS_NULOS varchar(255),
QTD_VOTOS_LEGENDA varchar(255),
QTD_VOTOS_ANULADOS_APU_SEP varchar(255),
DATA_ULT_TOTALIZACAO varchar(255),
HORA_ULT_TOTALIZACAO varchar(255)
);

-- load files
.mode csv
.separator ;
.import candidatos.txt candidato
.import detalhe_votacao.txt detalhe_votacao

delete from candidato where CODIGO_CARGO != 11;

CREATE INDEX IDX_DET_COD_MUNICIPIO on detalhe_votacao (CODIGO_MUNICIPIO);
CREATE INDEX IDX_CAND_COD_MUNICIPIO on candidato (CODIGO_MUNICIPIO);
create INDEX IDX_PREFEITO_MINICIPIO on candidato (ANO_ELEICAO, NUM_TURNO, SIGLA_UF, SIGLA_UE, CODIGO_MUNICIPIO, NOME_MUNICIPIO, NUMERO_CAND, SQ_CANDIDATO, NOME_CANDIDATO, NOME_URNA_CANDIDATO, DESC_SIT_CAND_TOT, NUMERO_PARTIDO, SIGLA_PARTIDO);
CREATE INDEX IDX_MUN_2_T_W on detalhe_votacao (CODIGO_CARGO);
CREATE INDEX IDX_MUN_2_T_GB on detalhe_votacao (CODIGO_MUNICIPIO, NOME_MUNICIPIO);
CREATE INDEX IDX_PREF_MUN_W on candidato (CODIGO_CARGO);
CREATE INDEX IDX_PREF_MUN_GB on candidato (NOME_MUNICIPIO);
CREATE INDEX IDX_TURNO on candidato (num_turno);
CREATE INDEX IDX_SQ_CAND on candidato (SQ_CANDIDATO);
CREATE INDEX IDX_NUM_CAND on candidato (NUMERO_CAND);
